
#definiciones de tipo nodo y terminación de la letra gestión
def f_diccionario_t_nodo_letra(nombre_nodo):
    diccionario_t_nodo_letra = {
        'MA5600T':'T',
        'MA5800':'M',
        'C300':'Z',
        'ISAM FX':'N'
    }
    if nombre_nodo not in diccionario_t_nodo_letra:
        return  ("NULL")
    return diccionario_t_nodo_letra[nombre_nodo]

#para definir el equipo y el numero de TLK.
def f_diccionario_equ_tlk(equipo):
    nro_modelo = equipo[0:2]
    #print (nro_modelo)
    #diccionario modelos
    modelo = {"70":"C300","71":"MA5600T","72":"C320","73":"MA5800","74":"ISAM FX"}
    if nro_modelo not in modelo:
        #print (equipo)
        return ("NULL")
    return (modelo[nro_modelo])

#diccionario para cada código telelink devuelve el nombre de gestión
def f_diccionario_tlk_gestion(cod_tlk):
    diccionario_tlk_gestion = {
        'ROC18JLO01':'18-JULIO',
        'FLIVCAGT01':'25-AGOSTO',
        'FLIVCMYO01':'25-MAYO',
        'MVDABYUM01':'ABAYUBA',
        'MVDAERTM01':'AEROPUERT',
        'MVDAERNM01':'AERO-NUEV',
        'MVDAGUAM01':'AGUADA',
        'MVDAGPKM01':'A-PARK',
        'CANAGCOR02':'AGUAS-COR',
        'ROCADLCS01':'AGUAS-DUL',
        'MLDAIGUA01':'AIGUA',
        'RNGALGRT01':'ALGORTA',
        'ARTARTGS01':'ARTIGAS',
        'MVDATAHM01':'ATAHUALPA',
        'CANATLNT01':'ATLANTIDA',
        'SJSATDRM01':'AUTODROMO',
        'TACBIPRA01':'BALIPORA',
        'MLDBSLIS01':'SOLIS',
        'COLBZGZU01':'ZAGARZAZU',
        'ARTBBRUM01':'B-BRUM',
        'MVDBCARM01':'BARRA-CAR',
        'ROCBVALZ01':'B-VALIZAS',
        'ROCBCHUY01':'BARR-CHUY',
        'CANBBLCS01':'B-BLANCOS',
        'CANBBLCS06':'BARRO-B-E',
        'CANBBLCS05':'BARRO-B-O',
        'SALBELEN01':'BELEN',
        'ARTBLLUN01':'B-UNION',
        'MLDBRRZN01':'BITZ-NOR',
        'MLDBRRZS01':'BITZ-SUR',
        'DURBLNQL01':'BLANQUILL',
        'MVDBUCEM01':'BUCEO',
        'MVDBRDSM01':'BURDEOS',
        'CANCNLNS01':'CANELONES',
        'CANCNLNS03':'CAN-ECHEV',
        'CANCNLNS05':'CAN-CADEN',
        'CANCNLNS08':'CAN-R11-N',
        'CANCNLNS06':'CAN-R11-S',
        'CANCNLNS07':'CAN-R5',
        'CANCNLNS04':'CAN-VALDE',
        'FLICADAL01':'CARDAL',
        'SORCRDNA01':'CARDONA',
        'DURCRYLS01':'C-REYLES',
        'COLCRMLO01':'CARMELO',
        'DURARMEN01':'CARMEN',
        'MVDCARRM01':'CARRASCO',
        'MVDCSBOM01':'CASABO',
        'MVDCSVLM01':'CASAVALLE',
        'ROCCSTLL01':'CASTILLOS',
        'FLICSPAF01':'CASUPA',
        'ROCCBOTI01':'CEBOLLATI',
        'MVDCRIOM01':'CENTENAR',
        'MVDCTROM01':'CENTRO',
        'MVDCITOM01':'CERRITO',
        'MVDCERRM01':'CERRO',
        'TYTCCATO01':'C-CHATO',
        'FLICCFDA01':'CRO-COLOR',
        'MVDCNT1M01':'CRO-NRTE1',
        'MVDCNT2M01':'CRO-NRTE2',
        'MLDCPLDM01':'CRO-PELAD',
        'FLICHMZO01':'CHAMIZO',
        'ROCCHUYY01':'CHUY',
        'MVDCVJAM01':'C-VIEJA',
        'MVDCO1LM01':'COLON',
        'COLCLNIA01':'COLONIA',
        'SJSCETRE01':'C-ETCHEPA',
        'COLCMGLT01':'COL-MIGUE',
        'CANSTRTA05':'C-NICOLIC',
        'COLCVLDN01':'C-VALDENS',
        'COLCNCHS01':'CONCHILLA',
        'SALCNION01':'CONSTITUC',
        'MVDCORDM01':'CORDON',
        'CANLFSTA05':'COSTA-AZL',
        'CANCALTA01':'CUCH-ALTA',
        'SALDFNSA01':'DEFENSA',
        'SORDLRES01':'DOLORES',
        'DURDUZNO01':'DURAZNO',
        'SJSEPLLR01':'ECILDA-P',
        'COLEGNRL01':'EL-GENERA',
        'CANEPRAR01':'EL-PINAR',
        'CANEOLMS01':'E-OLMOS',
        'TYTENRMZ01':'ENRIQUE-M',
        'CANATLNT02':'E-ATLANTI',
        'CANLFSTA06':'E-FLOREST',
        'MVDEUSKM01':'EUSKAL',
        'MLDFJIGN01':'FJ-IGNACI',
        'FLIFLRDA01':'FLORIDA',
        'CLGFMRTO01':'FRAILE-MU',
        'RNGFYBTS01':'F-BENTOS',
        'FLIFYMRC01':'F-MARCOS',
        'MLDGAZNR01':'G-AZNAREZ',
        'PAYGCHON01':'GUICHON',
        'FLEICRTN01':'ISMAEL-CO',
        'MVDITUZM01':'ITUZAINGO',
        'CANJUBRY01':'JAUREGUIBERR',
        'CANJNICO01':'JOANICO',
        'LAVBTLLE01':'J-BATLL-O',
        'MVDPRODM01':'JE-RODO',
        'LAVVRELA01':'JP-VARELA',
        'COLJLCZE01':'J-LACAZE',
        'SJSKIYUU01':'KIYU',
        'MLDLBRRA01':'LA-BARRA',
        'ROCCRLLL01':'LA-CORONI',
        'CANLFSTA01':'FLORESTA',
        'ROCLPRCH01':'LA-PALOMA',
        'MVDLPLAM01':'L-PAL-MVD',
        'CANLAPAZ01':'LA-PAZ',
        'ROCLPEDR01':'L-PEDRERA',
        'MVDLRDNM01':'L-REDENCI',
        'CANLTUNA01':'LA-TUNA',
        'CLGLMRIN01':'LGO-MERIN',
        'MLDLGSAU01':'LAG-SAUCE',
        'RNGLCAÑS01':'LAS-CAÑAS',
        'CANLPDRS01':'L-PIEDRAS',
        'CANLPDRS09':'L-PI-ESTE',
        'CANLPDRS06':'L-PI-RUT5',
        'ROCLSCNO01':'LASCANO',
        'MVDLEZCM01':'LEZICA',
        'SJSLIBTD01':'LIBERTAD',
        'CANSTRTA04':'LOMAS-CAR',
        'CANCRROS01':'CERRILLOS',
        'MLDMLDND01':'MALDONADO',
        'MVDMALVM01':'MALVIN',
        'MVDMG1AM01':'MANGA',
        'MVDMG2AM01':'MANGA-SA1',
        'MVDMG3AM01':'MANGA-SA2',
        'MVDMG4AM01':'MANGA-SA3',
        'LAVMRSCL01':'MARISCALA',
        'CANMLLLA01':'MELILLA-C',
        'MVDMLLAM01':'MELILL-MV',
        'CLGMELOO01':'MELO',
        'FLIMNDZA01':'MENDOZA',
        'SORMRCDS01':'MERCEDES',
        'CANMGUES01':'MIGUES',
        'LAVMINAS01':'MINAS',
        'RIVMNSCR01':'MCORRALES',
        'ARTMSQNT01':'MONES-QUI',
        'CANMNTES01':'MONTES',
        'COLNHLVC01':'N-HELVECI',
        'COLNPLMR01':'N-PALMIRA',
        'RNGNVBLN01':'N-BERLIN',
        'MVDNVPSM01':'NVO-PARIS',
        'COLOMLVE01':'OMBUES-LA',
        'SJSORDPT01':'O-D-PLATA',
        'MVDPJBLM01':'P-BLANCAS',
        'MVDPCIOM01':'PALACIO',
        'SORPLTAS01':'PALMITAS',
        'MLDPAZCR01':'P-AZUCAR',
        'CANPNDOO01':'PANDO',
        'CANPNDOO05':'PANDO-SUR',
        'MLDPRDA501':'PARADA-5',
        'LAVPQVAC01':'PQUE-VACA',
        'CANPDPTA01':'PQ-PLATA',
        'MVDPRODM01':'PQUE-RODO',
        'MVDPCARM01':'PASO-CARR',
        'MVDPANAM01':'P-ARENA',
        'MVDPAOEM01':'P-ARENA-O',
        'TACPDTRS01':'P-TOROS',
        'MVDPASOM01':'P-MOLINO',
        'PAYPYSND01':'PAYSANDU',
        'PAYPYSNN01':'PAY-NORTE',
        'MLDPNNSL01':'PENINSULA',
        'PAYPCLRS01':'PI-COLORA',
        'CANPAFLR01':'PI-AFILAR',
        'LAVPRARJ01':'PIRARAJA',
        'MLDPRPLS01':'PIRIAPOLI',
        'COLPFMNT01':'P-FOMENTO',
        'SJSPYPCL01':'P-PASCUAL',
        'MLDPYVRD01':'P-VERDE',
        'MVDPOCIM01':'POCITOS',
        'MLDPTZLO01':'PORTEZUE',
        'CANPRGSO01':'PROGRESO',
        'CANPRGSO05':'PROG-EMR5',
        'CANPRGSO04':'PROG-ESTE',
        'MVDPTACM01':'P-CARRETA',
        'ROCPTDBL01':'P-DIABLO',
        'MVDPLLOM01':'P-ESPINIL',
        'MLDPPDRA01':'P-PIEDRAS',
        'MVDPTRLM01':'P-RIELES',
        'SJSPVDEZ01':'P-VALDEZ',
        'PAYQBRCH01':'QUEBRACHO',
        'SJSRPZZA01':'R-PERAZZA',
        'COLRSCRL01':'R-S-CARLO',
        'FLIRBLDO01':'REBOLEDO',
        'MLDRDIND01':'R-INDIO',
        'CLGRBNCO01':'R-BRANCO',
        'RIVRVERA01':'RIVERA',
        'ROCROCHA01':'ROCHA',
        'SJSRDRGZ01':'RODRIGUEZ',
        'COLROSIO01':'ROSARIO',
        'CANSLNAS01':'SALINAS',
        'CANSLNAS06':'SALINAS-E',
        'SALSALTO01':'SALTO',
        'CANSNTOS01':'S-ANTONIO',
        'CANSBTTA01':'S-BAUTIST',
        'MLDSCRLS01':'S-CARLOS',
        'TACSGRIO01':'SG-POLANC',
        'CANSJITO01':'S-JACINTO',
        'RNGSNJVR01':'S-JAVIER',
        'SJSSJOSE01':'SAN-JOSE',
        'CANSJSCO01':'SJ-CARRAS',
        'CANSRMON01':'S-RAMON',
        'COLSTNCL01':'S-ANA',
        'SORSCTLN01':'S-CATALIN',
        'TYTOLMAR01':'S-CLARA',
        'CANSLCIA01':'S-LUCIA',
        'CANSROSA01':'STA-ROSA',
        'ROCSTERO01':'S-TERESA',
        'CANSTRTA01':'S-TERESIT',
        'CANSTRTA06':'S-TSITA-N',
        'MVDSVASM01':'S-VAZQUEZ',
        'DURSIDYI01':'SARAND-YI',
        'FLISDGDE01':'SARANDI-G',
        'CANSAUCE01':'SAUCE',
        'CANSAUCE04':'SAUCE-SUR',
        'MVDSYGOM01':'SAYAGO',
        'COLINIAA01':'SEMILLERO',
        'CANSOCAA01':'SOCA',
        'LAVSMTJO01':'SOLIS-MAT',
        'CANSLMAR01':'SOLYMAR',
        'CANSLMAR02':'SOLYMAR-E',
        'CANSUREZ01':'SUAREZ',
        'CANSUREZ03':'SUAREZ-N',
        'TACTCRMB01':'TACUAREMB',
        'CANTALAA01':'TALA',
        'CANTPIAA01':'TAPIA',
        'COLTRRAS01':'TARARIRAS',
        'PAYTGVYU01':'T-GUAVIYU',
        'SALTARPY01':'T-ARAPEY',
        'SALTDYMN01':'T-DAYMAN',
        'CANTLEDO01':'TOLEDO',
        'CANTLEDO06':'TOLEDO-E',
        'CANTLEDO01':'TOLEDO-O',
        'CANTLEDO04':'TOELDO-S',
        'ARTTGMSR01':'T-GOMENSO',
        'CANTTRAL01':'TOTORAL',
        'RIVTQRAS01':'TRANQUERA',
        'TYTTRYTR01':'T-Y-TRES',
        'FLETRNDD01':'TRINIDAD',
        'SJSTVJAS01':'TROPAS-VI',
        'CLGTPBAE01':'TUPAMBAE',
        'MVDUNIOM01':'UNION',
        'ROCVLZQZ01':'VELAZQUEZ',
        'TYTVRGRA01':'VERGARA',
        'RIVVCHDR01':'VICHADERO',
        'RNGYOUNG01':'YOUNG',
        'LAVZPCAN01':'ZAPICAN',
        'RNGZFFYB01':'ZF-FRAY-B',
        'MVDANARM01':'A-ARENA'

    }
    if cod_tlk not in diccionario_tlk_gestion:
         return ("NULL")
    return diccionario_tlk_gestion[cod_tlk]

def f_nombre_gestion (tlk,nro_nodo,tipo_nodo):
    
    nombre_gestion = ""
    nro_nodo_txt ="-"
    nombre_gestion = f_diccionario_tlk_gestion(tlk)

    if nro_nodo <10:
        nro_nodo_txt = nro_nodo_txt +"0"+ str(nro_nodo)
    else:
        nro_nodo_txt = nro_nodo_txt + str (nro_nodo)

    nombre_gestion =nombre_gestion + nro_nodo_txt + f_diccionario_t_nodo_letra(tipo_nodo)

    return nombre_gestion




#print (f_nombre_gestion ("RNGYOUNG01",15,""))

